      - name: Get FriendWork jobs
        run: |
          curl -X GET \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header "Authorization: Bearer ${{ secrets.FRIENDWORK_API_TOKEN }}" \
            -d '{
              "statuses": ["open", "onHold"],
              "paging": { "page": 0, "count": 5 }
            }' \
            'https://api.friend.work/jobs' > jobs.json
